project_films_homepage:

    resource: "@ProjectFilmsBundle/Controller"
    type:     annotation

project_films_one:

    resource: "@ProjectFilmsBundle/Controller"
    type:     annotation

project_films_signup:
    resource: "@ProjectFilmsBundle/Controller"
    type:     annotation


project_films_addreview:
    path:     /addreview
    defaults: { _controller: ProjectFilmsBundle:Default:review}