project_films_homepage:

    resource: "@ProjectFilmsBundle/Controller"
    type:     annotation

project_films_one:

    resource: "@ProjectFilmsBundle/Controller"
    type:     annotation

project_films_hobbit:
    resource: "@ProjectFilmsBundle/Controller"
    type:     annotation

project_films_signup:
    resource: "@ProjectFilmsBundle/Controller"
    type:     annotation

project_films_new:
    path:     /new
    defaults: { _controller: "ProjectFilmsBundle:Default:new" }

login:
 pattern: /login
 defaults: { _controller: ProjectFilmsBundle:Default:login }

login_check:
 pattern: /login_check

logout:
    path:     /logout

project_films_review:
    path:     /review
    defaults: { _controller: "ProjectFilmsBundle:Default:review"}

project_films_listreviews:
    path:     /listreviews
    defaults: { _controller: "ProjectFilmsBundle:Default:listreviews"}

